### ISSUE TITLE
add third-party licensing notices

### ISSUE THREAD

**Issue by cbalster** [criticalmaps/criticalmaps-android#114]
...to comply with their licenses.
I already have most of them collected but am unsure where best to add them. Maybe add another header in about and list the names there and expand on click? Or maybe just a link in about and show them in a separate activity?

**Comment by stephanlindauer** [comment]
i vote for having another header in the about section. maybe somewhere a bit further below the fold. :P

**Comment by cbalster** [comment]
added in #136
