### ISSUE TITLE
Encrypt the communication with HTTPS

### ISSUE THREAD

**Issue by bastei** [criticalmaps/criticalmaps-android#19]
Unfortunately the communication between the app and criticalmaps.net is unencrypted. A corresponding information made it to the [app description on F-Droid](https://f-droid.org/repository/browse/?fdid=de.stephanlindauer.criticalmaps).
As locations and (anonymous) messages are quite sensitive data it would be preferable to use encrypted HTTPS-connections.

**Comment by stephanlindauer** [comment]
valid point. we'll migrate our backend soon and will setup https there. our current hosting provider charges unreasonable prices for certification.

**Comment by stephanlindauer** [comment]
@cbalster @ligi @johnjohndoe 
i will setup https encryption with a self-signed certificate if you don't have any objections. (?)

**Comment by ligi** [comment]
another option would perhaps be a free certificate from let's-encrypt ( https://letsencrypt.org/ ) - but a self signed one is also completely OK for this use-case

**Comment by cbalster** [comment]
+1 for letsencrypt

**Comment by stephanlindauer** [comment]
looks interesting. will look into that as soon as i have a working 
infrastructure on http.

**Comment by Wikinaut** [comment]
@stephanlindauer Let's Encrypt is very easy to deploy; from https://letsencrypt.org/getting-started/  your final destination should be https://certbot.eff.org/ .

**Comment by stephanlindauer** [comment]
i know i know. and this is somoething i want to get done as soon as possible. 
the plan is to pull all those services into my kubernetes cluster and do the tls in the ingress controllers.
is jsut dont have time currently because i'm wrriting my master thesis. will get to it in march.

**Comment by stephanlindauer** [comment]
@headione how fast can u move all your users to https? should we probably keep both ports open until an significant junk of users has been moved to https? can we implement something like "try https, if it fails, use http"

**Comment by Wikinaut** [comment]
On your (http) server, you could rewrite all http accesses to https 

```
<VirtualHost *:80>
        ServerName example.org
        ServerAlias www.example.org
        DocumentRoot /......

        RewriteEngine On

        RewriteCond %{SERVER_NAME} =www.example.org [OR] 
        RewriteCond %{SERVER_NAME} =example.org
        RewriteRule ^ https://www.example.org%{REQUEST_URI} [END,QSA,R=permanent]
</VirtualHost>

```

The served https page/s must not contain references to non-https content (images, css, js,....) to avoid "mixed-content" warnings.


On https://github.com/Wikinaut/MySimpleCertificateViewer I have published a simple certificate viewer, which might be of help when developing.

**Comment by cbalster** [comment]
This is resolved at least for the website and the android app with the new backend .
