### ISSUE TITLE
OSM map not loaded on start

### ISSUE THREAD

**Issue by Wikinaut** [criticalmaps/criticalmaps-android#211]
With the recent versions I noticed that the map is not loaded when the app is started, when GPS is switched off.

I only see a blue map with my own position icon, zoom-in or zoom-out: no function.

* HUAWEI P8 Lite 2017
* Android 7.0

**Comment by cbalster** [comment]
I will take a look at this today. I noticed some quirks with the osmdroid cache while upgrading the targetSdk - maybe this is related.

**Comment by cbalster** [comment]
Can you please tell me if you denied the external storage permission for the app? Even though this should be unrelated to gps settings.

**Comment by Wikinaut** [comment]
@cbalster All three permission are **given** (storage, location and camera).

**Comment by cbalster** [comment]
I finally found some time to work on the app. I can't reproduce your problem, but I made some changes that also concern osmdroid's cache. These probably also solved your issue. Can I supply you with a test version in some way?

**Comment by Wikinaut** [comment]
@cbalster just make a new branch here which I can then fetch into my repo.

**Comment by cbalster** [comment]
Sure, I pushed my wip branch here: https://github.com/cbalster/criticalmaps-android/tree/osmdroid_test

**Comment by Wikinaut** [comment]
Ich habe gerade Deine Version gebaut und geladen --> "blaues Wasser" beim Start (GPS ist ausgeschaltet), weil Koordinaten 0,0 sind? Vielleicht kann man für diesen Fall das Fahrradsymbol (so wie das dann-rote GPS-Symbol) auch inaktiv darstellen (z.B. mit einem roten X übermalen?)

Vielleicht.... ist mein ursprünglicher Fehlerreport oben auch ein "falscher" Fehler gewesen und ich hätte nur massiv herauszoomen müssen?

**Comment by Wikinaut** [comment]
I am closing this issue now. May be my mistake (not having zoomed-out enough to see the map).

**Comment by cbalster** [comment]
Ganz ohne location startet die app eigentlich ohne das Icon und komplett herausgezoomt. Wenn du trotz deaktiviertem GPS bei 0,0 und reingezoomt bist und das Icon angezeigt wird, dann kommt die Info von der lastKnownLocation. Wenn die "alt" ist, könnte man das zB über ein ausgegrautes Icon kenntlich machen. Was mich verweundert ist, dass die location 0,0 ist - ist neben deaktiviertem GPS bei dir XPrivacy oder so installiert, dass diesen Wert als default liefern könnte?

**Comment by Wikinaut** [comment]
Habe ich nicht installiert.
