### ISSUE TITLE
Publish App to F-Droid (Free Open Source App Store)

### ISSUE THREAD

**Issue by rradar** [criticalmaps/criticalmaps-android#222]
Please **do it**! It's missing and me and all other google free people can't install this (probably) great app!

> https://f-droid.org/
> 
> To request a new app be added, submit a “Request For Packaging” on the rfp tracker: https://gitlab.com/fdroid/rfp/issues/new

Meanwhile the app itself (as .apk) could also be released here (github) in the release section! :+1:

**Comment by rradar** [comment]
Nice! Ticket #222 :1st_place_medal:

**Comment by ligi** [comment]
https://f-droid.org/packages/de.stephanlindauer.criticalmaps/ ;-)

**Comment by rradar** [comment]
That was quick! :+1:
