### ISSUE TITLE
Round Launcher Icon

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-android#238]
Instead of showing the old square icon in a circle on new Android versions we should implement [adaptive launcher icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html) or at least a true round icon. (not sure if there's a difference)

![2315234](https://user-images.githubusercontent.com/888679/53272875-bfd67800-36f2-11e9-8e5d-734528bf6363.jpg)

![786574](https://user-images.githubusercontent.com/888679/53272877-c06f0e80-36f2-11e9-90c6-8d945a302dc4.jpg)

**Comment by cbalster** [comment]
implemented in #240
