### ISSUE TITLE
High resolution map tiles

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-android#248]
Provide high resolution map tiles depending on the DPI of the device. Supported scales are 1.3, 1.5, 2, 2.6, 3

Documentation: https://www.mediawiki.org/wiki/Wikimedia_Maps/2015-2017/Technical_Implementation

**Comment by cbalster** [comment]
my idea is:

- automatically determine scale factor to use by the device's screen density
- make this configurable with a setting "Map quality" with the options "High resolution" and "Normal" description "High resolution looks better but uses more data"

**Comment by cbalster** [comment]
implemented in #299
