### ISSUE TITLE
Update Policy

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-android#253]
<table>
<tr>
<th>current</th>
<th>new (dark)</th>
<th>new (light)</th>
</tr>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/888679/56265735-9fbba780-60ea-11e9-8289-ed49aecf6ccf.png" width="240" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/888679/56265736-a0543e00-60ea-11e9-9483-08244fe08cc9.png" width="240" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/888679/56265737-a0543e00-60ea-11e9-92c2-e04e08cc9ede.png" width="240" />
</td>
</tr>
</table>

The GPS permission dialog should be triggered when hitting the "confirmation" button, not before that.

**Comment by askarsyzdykov** [comment]
I'm taking this task, ok?

**Comment by cbalster** [comment]
Sure!

**Comment by askarsyzdykov** [comment]
Miss click 😬

**Comment by cbalster** [comment]
resolved by #291
