### ISSUE TITLE
Add Russian locale

### ISSUE THREAD

**Issue by askarsyzdykov** [criticalmaps/criticalmaps-android#266]
Hi, I'm translating your app on https://www.transifex.com/criticalmaps/criticalmaps/ to Russian language. Should I create PR with values-ru, or it will be created automatically?

**Comment by cbalster** [comment]
Hi Askar, thanks for contributing!

You can update the Russian xml file via txpull and then open a PR if you
like. Otherwise I will merge it in the next days.
