### ISSUE TITLE
Add Japanese locale

### ISSUE THREAD

**Issue by CptMaister** [criticalmaps/criticalmaps-android#268]
Hello, I translated your app on https://www.transifex.com/criticalmaps/criticalmaps/ to Japanese. What will be the next step? Will the translation be merged automatically?

Thank you so much for maintaining Critical Maps, it's really useful in our local bike community and will be essential for our plans for daily Critical Masses to university :-)

**Comment by cbalster** [comment]
Thank you for the contribution!
