### ISSUE TITLE
Hidden option to set alternative server for debugging

### ISSUE THREAD

**Issue by weliveindetail** [criticalmaps/criticalmaps-android#271]
At the moment the app can only be tested with the production server. In order to test it with historical or manufactured data it would be useful to add an option for an alternative server URL in the `Settings` screen.

We talked about it at CycleHack and came up with this proposal:
* The option should not confuse the regular user. Instead, the it could be hidden until the developer e.g. tapped 3 times on the `Map settings` heading.
* Typing custom URLs every time we test the app is cumbersome, instead we could scan it from a QR code.
* We will forget to reset the option. It would be convenient to reset it automatically (after 5 hours / at the end of the day / when the app is closed).

**Comment by cbalster** [comment]
Sounds good!
Maybe making that option visible only for debug builds might be another
option. Do you see any use case for also having access to this in a release
build?

**Comment by weliveindetail** [comment]
Maybe it's easier for the community to verify bugs/fixes on their devices, if it doesn't require to build and deploy a debug version.

**Comment by cbalster** [comment]
True, this might be helpful. I'd be fine with the "tap three times" option. :)
