### ISSUE TITLE
Option "Searching"

### ISSUE THREAD

**Issue by mega-stoffel** [criticalmaps/criticalmaps-android#274]
it might be a good idea to bring an option "Searching" to the app. This option would hide your location, but you could still see all others. It might be helpful in smaller cities, where the CM has only a few Critical Maps users, and as much, if not even - in some cases - more people looking for the current CM.
To avoid forgetting this option: as soon as your location is close to somebody else, the option "Searching" could automatically be deactivated and the app is back in the "normal" mode.

**Comment by dreua** [comment]
I'm wondering if leaving the searchers on the map but showing them in another color or another icon would be a better solution to your problem. Unless that is prohibitively harder to implement I think the position of searchers could still be valuable in some cases.

**Comment by cbalster** [comment]
Closing this for now - if you have any feedback on the observer mode once it's rolled out, just open a new issue :)
Thank you for the feedback!
