### ISSUE TITLE
Wrong color for center location icon FAB on API 21 after fragment change

### ISSUE THREAD

**Issue by cbalster** [criticalmaps/criticalmaps-android#304]
On API21, on first load of the map fragment the color is correct. After switching to another fragment and returning to the map fragment the icon is white instead of black. Probably some issue with the underlying button state definition.

![API21_center_location_state](https://user-images.githubusercontent.com/9266843/79636259-b326a600-8176-11ea-8ac3-798ee4f7b109.png)

**Comment by askarsyzdykov** [comment]
@cbalster check plz https://github.com/criticalmaps/criticalmaps-android/pull/310

**Comment by cbalster** [comment]
fixed by #310
