### ISSUE TITLE
define a secret token to make it slighty harder to use the api

### ISSUE THREAD

**Issue by stephanlindauer** [criticalmaps/criticalmaps-android#39]
set auth header. 
on the server: refuse write, allow read for backwards compatibility.
set a dummy token in the public repo and hand out the dev token to all contributors.

**Comment by keeba0** [comment]
This would break F-Droid-builds as long as the dummy token is meant to be non-functional. As F-Droid-builds have to be 100% reproducible, all of the code has to be public.
Nevertheless, the MozStumbler Andoird-app for example has an own flavour meant for F-Droid-builds that provides [an API key](https://github.com/mozilla/MozStumbler/blob/dev/android/properties/private-fdroid.properties).
There was also a [discussion about that topic in the F-Droid Server issues](https://gitlab.com/fdroid/fdroidserver/issues/45).

**Comment by stephanlindauer** [comment]
i havent really thought about that yet. thanks for pointing that out.
maybe we can find ways to make our api less exposed to attacks by implementing some kind of attack detection that just ignores malicious behaviour. i will get back to you in this.

**Comment by stephanlindauer** [comment]
i think we can just close this. when we notice malicious behavior, we should let the backend do the locking out of users by blocking their device.
lets look into that when i have pushed the legacy backend code so we can properly make plans on how to build a new one with those kinds of mechanics.

**Comment by cbalster** [comment]
:+1:
