### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by stephanlindauer** [criticalmaps/criticalmaps-android#42]
![image](https://cloud.githubusercontent.com/assets/1323145/10117212/25d12418-644f-11e5-9c56-bcc3bab2d7c2.png)

**Comment by cbalster** [comment]
Okay, I think I know what's going on: There's an exception thrown in the http studd, but there is no Handler bound to the worker thread that provides output to System.err required for e.printstacktrace.
See: http://developer.android.com/reference/java/util/logging/ConsoleHandler.html
I'll push a fix in a minute.

**Comment by stephanlindauer** [comment]
i tested the potential fix on an htc sensation and it still breaks. looking at this stackoverflow comment http://stackoverflow.com/a/16834783/1699932, i think we need to run it on the UI thread and not in the seperate service thread. which also brings up the question: will the activity and its thread still be there when the service needs to do stuff on it?

i will have a deeper look into that next week.

**Comment by cbalster** [comment]
Oh, to be honest I didn't even realize the service ran in it's own process. IMHO there is no need to do so and I think we can just safely let it run on the main thread. I still don't get why this error is device-specific though...

**Comment by cbalster** [comment]
Wait, scratch that. I think I had a minor lapse in reading skills yesterday and accidently misread the "android:process" tag to be defined for the service ;)
So no, the process does not run in it's own process, so this can not be the issue.
Also, as far as I can tell there is nothing in doInBackground(), that calls anything which should only be run from the UI thread. The only thing I can see that is potentially problematic, is the fact that we're reading values and calling methods from the main thread in there. But again this should only possibly cause memory visibility problems and not cause that kind of crash....

**Comment by cbalster** [comment]
okay, this time for real. tested on emulator.
