### ISSUE TITLE
Return correct content type

### ISSUE THREAD

**Issue by johnjohndoe** [criticalmaps/criticalmaps-android#53]
The JSON response from the **API** does **not** return the correct content type:

```
$ curl -s -D - http://api.criticalmaps.net/twitter/get.php

HTTP/1.1 200 OK
Date: Sun, 04 Oct 2015 22:27:23 GMT
Server: Apache
X-Powered-By: PHP/5.4.44
Transfer-Encoding: chunked
Content-Type: text/html
```

It should be `Content-Type: application/json;charset=utf-8` instead.

**Comment by johnjohndoe** [comment]
I opened a [new issue](https://github.com/criticalmaps/criticalmaps-web/issues/1) for the correct repository.

**Comment by johnjohndoe** [comment]
Since the API is not yet published I reopen this issue to being fixed asap.

**Comment by johnjohndoe** [comment]
You will be happy to see pretty formatted output in your browser as soon as the response type is correct and you use an add-on such as *JSONView* for [Chrome](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en) or [Firefox](https://addons.mozilla.org/en-us/firefox/addon/jsonview/).

**Comment by johnjohndoe** [comment]
Any news here since https://github.com/criticalmaps/criticalmaps-api is out?

**Comment by stephanlindauer** [comment]
i haven't really started to port that logic to the new system. i am kinda stuck right now finding the right setup to properly scale the servers up and down.

**Comment by stephanlindauer** [comment]
ok fixed for /postv2
just a temporary solution though

**Comment by stephanlindauer** [comment]
i will close this issue after this will automatically work with the puma + sinatra setup
if you need more endpoints to have this header for now just reopen the issue

**Comment by johnjohndoe** [comment]
I suppose you want to say that you are switching `http://api.criticalmaps.net/twitter/get.php` from *HTTP GET* to *HTTP POST*? I could however not confirm `application/json;charset=utf-8` is returned as a content type. Can you please link to the specific code snippet of the API? I could maybe help to configure the content type for the endpoint.
