### ISSUE TITLE
take screenshots during the next cm in berlin

### ISSUE THREAD

**Issue by stephanlindauer** [criticalmaps/criticalmaps-android#83]
...to showcase the app in the repo and to have new screenshots for the play store

**Comment by ligi** [comment]
Yea - and let's meet there - really hope there will be no rain or snow ;-)

On 14.10.2015 18:37, stephan lindauer wrote:
> ...to showcase the app in the repo and to have new screenshots for the
> play store
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/criticalmaps/criticalmaps-android/issues/83>.
> 


-- 
best regards,
ligi
http://ligi.de

**Comment by cbalster** [comment]
:+1:

**Comment by stephanlindauer** [comment]
:+1:

**Comment by stephanlindauer** [comment]
added new screenshots to the google play store
