### ISSUE TITLE
Should we temporarily remove the Sternfahrt feature?

### ISSUE THREAD

**Issue by cbalster** [criticalmaps/criticalmaps-android#88]
While we probably all agree this is a feature that should be included, right now it has some problems:
- long initial dynamic generation
- impact on performance
- only relevant to berlin

In a short discussion with @ligi we agreed, that we all should probably put some thought in redesigning the feature (different cities, only specific routes, ...). I proposed temporarily removing the feature until this is sorted out, but ligi correctly pointed out that this might confuse users.
So, any thoughts about that?

**Comment by cbalster** [comment]
see #103

**Comment by stephanlindauer** [comment]
i was thinking about adding another fragment for settings. in that fragment we can have a more complex menu structure for enabling or disabling route overlays. this would make it possible to add more ADFC routes or even bicycle highways for example.
one thing that would also significantly improve performance would be thinning out the coordinates to have a minimum distance of ~3 m or so. back then they were waaaaaay to accurate.

what do you think?

are you guys on board with adding another branch on the main repository to get started with this?
