### ISSUE TITLE
UX Maximize screen real-estate

### ISSUE THREAD

**Issue by ligi** [criticalmaps/criticalmaps-android#89]
As I user I would like to see the as much map as possible when the phone is mounted to bike while cm.

When the phone detects that there was no user input for a while 
Then the  Actionbar should disappear

When the phone detects that there is userinput
And the Actionbar is invisible
Then the Actionbar should appear

**Comment by zutrinken** [comment]
In #239 the Actionbar is floating. Not like described here, but still shows more map and matches the initial idea. Good enough I'd say ...
